### ISSUE TITLE
New logo for OCRserver

### ISSUE THREAD

**Issue by reallinfo** [otiai10/ocrserver#14]
I wanted to contribute to OCRserver I designed a logo for OCRserver. If you like it, I'll send you the all files.

![1](https://user-images.githubusercontent.com/36298335/38117165-3c81145e-33bc-11e8-90aa-ba6fb45b400a.jpg)
![2](https://user-images.githubusercontent.com/36298335/38117166-3ca90126-33bc-11e8-987e-0215a4c243b3.jpg)

**Comment by otiai10** [comment]
It seems good idea to use letters, however, I don't like circle based logo very much.
What is the reason for using circle as main design scheme?

**Comment by reallinfo** [comment]
Is there anything you want to change? I can design according to you wish.

**Comment by otiai10** [comment]
I believe it's not easy work to think about design scheme of any services because it's very important to know the services well, how it works, why it's made, where and when it's used, etc...

And, for now, I don't have any resources to think about graphical stuff including listing up my wish for the logo.

I really appreciate your creativity, but I want you (or me) to think deeply to make the face of this software, not as a piece of cake on the side.
