### ISSUE TITLE
Any plan to use gosseract develop branch for saving init cost？

### ISSUE THREAD

**Issue by wangsongyan** [otiai10/ocrserver#19]
I found that this client's init method cost a lot of time while using ocrserver. Any plan to use gosseract develop branch for saving init cost, or some suggestions for me?

**Comment by otiai10** [comment]
On which environment do you have this server running? If you have it running manually, you can just update your `gosseract` version located under `$GOPATH/src/github.com/otiai10` and rebuild your server.

If you are using Docker / docker-compose, that's because I didn't push the newest Docker image built with the refined `gosseract`. I'm going to push that anyway. Thx.

**Comment by wangsongyan** [comment]
I run this server manually, and update ```gosseract``` version with go mod.  But this server cannot use the ```shouldInit``` feature, because there is a new gosseract client for every http connection.

**Comment by otiai10** [comment]
ah, got it
